[package]
name = "renet-transport-naia-webrtc-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renet = "0.0.13"
renetcode = "0.0.9"
log = "0.4.17"
naia-server-socket = "0.20.0"

